### ISSUE TITLE
Fix docker-machine rm command

### ISSUE THREAD

**Issue by shouze** [scaleway/docker-machine-driver-scaleway#17]
Given I want to remove a docker machine
When I execute the command
```shell
$ docker-machine rm test-docker-machine                                                                                                                                    About to remove test-docker-machine
Are you sure? (y/n): y
Error removing host "test-docker-machine": The method is not allowed for the requested URL.
```
Then I execute `docker ls`
And the output looks like
```shell
test-docker-machine            -        scaleway       Error                                                     Unknown   "95bdefdc-21c7-4487-a09c-b0e1adae59fb" not found
```

**Note**: the scaleway machine if effectively removed, running a consecutive `docker-machine rm -f` solve the problem on the docker side.

Environment:
- scaleway/scaleway/docker-machine-driver-scaleway: stable 1.0.1, HEAD
- docker-machine version 0.7.0, build a650a40

**Comment by moul** [comment]
Hi @shouze, thank you for your feedback,

@QuentinPerez was already working on this bug, it should be fixed by today

**Comment by QuentinPerez** [comment]
Hi @shouze,

The PR seems fixed this bug 😉
