### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by jmatsushita** [scaleway/docker-machine-driver-scaleway#19]
Any chance you'd be interested in also releasing binaries like done here for instance https://github.com/janeczku/docker-machine-vultr/releases ?

**Comment by moul** [comment]
Hi @jmatsushita,

Yes, sure

**Comment by moul** [comment]
Here they are: https://github.com/scaleway/docker-machine-driver-scaleway/releases/tag/v1.0.2
