### ISSUE TITLE
Here's as far as I get guys

### ISSUE THREAD

**Issue by faddat** [scaleway/docker-machine-driver-scaleway#24]
![selection_006](https://cloud.githubusercontent.com/assets/7142025/14765331/589f49b6-0a07-11e6-8fa2-cd559f0b4f3b.png)

**Comment by QuentinPerez** [comment]
Hi @faddat, thank you for your feedback,

Are you sure that it's your organization token ? I don't think so, it looks like `111111-...-....-...-111111`

You can find your organization (access key) token [here](https://cloud.scaleway.com/#/credentials)

Let me know if you need anything else.

**Comment by faddat** [comment]
AHA!  Okay, so-- the bug is not in code.  The bug is in terminology.  Guys, seriously:

It's an access key, not an organization.  Use the terminology consistently and *poof* problems, shall be gone.... :).
