### ISSUE TITLE
Select an existing IP on machine creation

### ISSUE THREAD

**Issue by Spy-Seth** [scaleway/docker-machine-driver-scaleway#37]
When creating a machine with the driver we cannot choose the machine IP. And if try to change it from the scaleway backend this break the link between the local docker machine and the actual machine.

**Comment by QuentinPerez** [comment]
Hi @Spy-Seth, thank you for your feedback

I added a subcommand `--scaleway-ip`  to specify an address IP, but I think you can change it in the JSON config:

```console
$ cat ~/.docker/machine/machines/yourmachine/config.json | head
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "X.X.X.X",  # <- here

```
