### ISSUE TITLE
Add instruction on installing precompiled driver

### ISSUE THREAD

**Issue by rudyryk** [scaleway/docker-machine-driver-scaleway#52]
It's unclear, how to install the precompiled binary version.

I suggest adding more details to documentation, like that:

1. Download a binary, e. g.

   `wget https://github.com/scaleway/docker-machine-driver-scaleway/releases/download/v1.2.1/docker-machine-driver-scaleway-linux-amd64`

2. Make it executable and place under the name `docker-machine-driver-scaleway` so it will be accessible in your PATH

   ```bash
chmod +x docker-machine-driver-scaleway-linux-amd64
sudo cp docker-machine-driver-scaleway-linux-amd64 /usr/local/bin/docker-machine-driver-scaleway
   ```

**Comment by QuentinPerez** [comment]
Hi @rudyryk, thank you for your feedback 😊

I updated the [README](https://github.com/scaleway/docker-machine-driver-scaleway/commit/f06eb18f0479425731f6e0c24ffbf4142d5975f2) to add your instructions.
