### ISSUE TITLE
Any plan on merging the driver upstream?

### ISSUE THREAD

**Issue by matm** [scaleway/docker-machine-driver-scaleway#53]
Docker Machine comes with many drivers for popular cloud providers already: https://github.com/docker/machine/tree/master/drivers.

Do you have any plan on merging this Scaleway driver to the `docker-machine` official repo?

**Comment by QuentinPerez** [comment]
Hi @matm,
Unfortunately the politic has changed https://github.com/docker/machine/pull/1389#issuecomment-126818120

**Comment by matm** [comment]
Thanks for your quick feedback @QuentinPerez. 

All of the current Machine drivers part of the official repo will be moved out, so the way to go is to have external repos for 3rd party drivers indeed.
