### ISSUE TITLE
Error starting plugin binary

### ISSUE THREAD

**Issue by terbooter** [scaleway/docker-machine-driver-scaleway#55]
```
root@local:~# docker-machine create -d scaleway -h
Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-scaleway: exec format error
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
root@local:~#
```

**Comment by QuentinPerez** [comment]
Hi @terbooter,

I think that you didn't download the binary which corresponds with your architecture

**Comment by terbooter** [comment]
Which binary should I use to install on virtual machine with ubuntu 64bit
```
uname -a
Linux local 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
run on host with windows7 64bit

**Comment by QuentinPerez** [comment]
Can you try with this binary ? https://github.com/scaleway/docker-machine-driver-scaleway/releases/download/v1.2.1/docker-machine-driver-scaleway_1.2.1_linux_amd64.tar.gz

**Comment by terbooter** [comment]
Thanks! This binary is working for my architecture
