### ISSUE TITLE
Error running docker-machine rm

### ISSUE THREAD

**Issue by rkyleg** [scaleway/docker-machine-driver-scaleway#61]
I get an error when trying to remove a node using `docker-machine rm`. My docker-machine command errored out, so the node wasn't actually created, but was registered in docker-machine. 

Error:
`Error removing host "node03": StatusCode: 405, Type: 405, APIMessage: The method is not allowed for the requested URL.`

The `rm` command works as expected if the node is successfully created on scaleway.

**Comment by pascalandy** [comment]
I actually do a `docker-machine rm -f NodeName` and it works great here :)
