### ISSUE TITLE
Explanation about generated tags

### ISSUE THREAD

**Issue by brikou** [scaleway/docker-machine-driver-scaleway#69]
After creating 2 machines with the scaleway driver, I found that some tags appears. What is the purpose of those, I don't understand?

![image](https://user-images.githubusercontent.com/383212/29244373-dbed1354-7fb6-11e7-8bd2-39b4e0c42ec4.png)

**Comment by tbillon** [comment]
The `AUTHORIZED_KEY` tag allows you to add a ssh key which is not from your account credentials.
I suppose the driver does this to allow the machine Docker Machine runs on to connect to the managed servers without having you add a specific key to your account.
