### ISSUE TITLE
Brew install archive sha256 mismatch

### ISSUE THREAD

**Issue by Gerrel** [scaleway/docker-machine-driver-scaleway#73]
brew install scaleway/scaleway/docker-machine-driver-scaleway
==> Installing docker-machine-driver-scaleway from scaleway/scaleway
==> Downloading https://github.com/scaleway/docker-machine-driver-scaleway/archive/v1.3.tar.gz
==> Downloading from https://codeload.github.com/scaleway/docker-machine-driver-scaleway/tar.gz/v1.3
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: 1f52d9cb308b0d94f96ab2d37113940408981c9986189126beb79c6ded7d4276
Actual: e30253c38cb3f43e66be2ca6dd9f58da870237002ee7a9a4a57d3a29bf45a0da

**Comment by maxbritto** [comment]
Had the same issue, had to use the latest git version instead of the release.
Use this command : 
`brew install scaleway/scaleway/docker-machine-driver-scaleway --HEAD`

**Comment by gardner** [comment]
I got the same message. Installing from with `--HEAD` works.

**Comment by sieben** [comment]
Thanks @gardner :)
