### ISSUE TITLE
Docker bootscript not compatible with Docker swarm mode

### ISSUE THREAD

**Issue by jaylinski** [scaleway/docker-machine-driver-scaleway#79]
I just wanted to let you know, that the default bootscript used by this driver is not compatible with Docker swarm mode.

I had to change my Ubuntu Xenial bootscript to `x86_64 mainline 4.4.105 rev1` in order to get swarm mode working, as described in issue https://github.com/scaleway/image-ubuntu/issues/78#issuecomment-333669414.

You should consider to either
* fix the docker bootscript
* change the default bootscript to mainline
* describe this issue in the readme file

Cheers! :whale:

**Comment by izissise** [comment]
"" Empty bootscript is now the default, thanks for reporting this issue
