### ISSUE TITLE
Gitlab CI Runners + (Docker+machine) on scaleway

### ISSUE THREAD

**Issue by coderhs** [scaleway/docker-machine-driver-scaleway#80]
I am using scaleway to run the GItlab CI workers. I am having an issue where the machines are not getting removed but just being shut down. Since they are not being removed, it will cost us money as the volumes are still being charged.

I am not quite clear on how to approach this problem, thus asking the question here.

**Comment by sieben** [comment]
There are 2 ways to turn off a machine on Scaleway:

- Archive (The default one that archives the volume)
- Terminate (That discard the volume)

Could you try to terminate the instance instead of archiving it? Those options are available inside the cloud.scaleway.com web console.

**Comment by dcharbonnier** [comment]
The request is to terminate instead of archiving when you do a `docker-machine rm` using the console is not an option

**Comment by dcharbonnier** [comment]
@coderhs https://github.com/dcharbonnier/docker-machine-driver-scaleway/commit/f74a854f516c945832350dedfc3f3f47c9edd760
