### ISSUE TITLE
tag new version

### ISSUE THREAD

**Issue by mathroc** [scaleway/docker-machine-driver-scaleway#89]
it would be nice to tag a new version sometime, the `--scaleway-bootscript=""` seems to be required now (couldn't find an image that worked without it)

**Comment by TRYDirect** [comment]
+1

**Comment by TRYDirect** [comment]
I get following error Error creating machine: Error in driver during machine creation: No such bootscript: docker\n",

**Comment by izissise** [comment]
"" Empty bootscript is now the default, so this parameter doesn't need to be be specified anymore
