### ISSUE TITLE
change default bootscript?

### ISSUE THREAD

**Issue by mathroc** [scaleway/docker-machine-driver-scaleway#90]
with the latest (see #89) version of the driver, we can create new machine but only if the `--scaleway-bootscript=""` is present. maybe it should be the default ? or the scaleway image should be fixed to add the `docker` bootscript?

> Error creating machine: Error in driver during machine creation: No such bootscript: docker

**Comment by izissise** [comment]
The default bootscript is now "" (empty string), so it'll get the default bootscript of the choosen image
