### ISSUE TITLE
Wrong commercial type

### ISSUE THREAD

**Issue by sieben** [scaleway/docker-machine-driver-scaleway#92]
```

$ docker-machine create --driver scaleway --scaleway-name sample-scaleway11.com --scaleway-image e20532c4-1fa0-4c97-992f-436b8d372c07 --scaleway-commercial-type "start1-s" sample-scadflkjdlkjfdlkjfddsds
Running pre-create checks...
Creating machine...
(sample-scadflkjdlkjfdlkjfddsds) Creating SSH key...
(sample-scadflkjdlkjfdlkjfddsds) Creating server...
Error creating machine: Error in driver during machine creation: START1-S wrong commercial type
```

**Comment by sedlund** [comment]
# docker-machine version
docker-machine version 0.16.0, build 702c267f

docker-machine create -d scaleway --scaleway-organization xxx --scaleway-token xxx test-machine
Running pre-create checks...
Creating machine...
(txr) Creating SSH key...
(txr) Creating server...
Error creating machine: Error in driver during machine creation: START1-S wrong commercial type

**Comment by bpoussin** [comment]
START-1S is not valid name, name must be:

C1, C2[S|M|L], X64-[2|4|8|15|30|60|120]GB, ARM64-[2|4|8]GB

"START-1S" is "X64-2GB"

**Comment by arttuka** [comment]
I have the same problem, trying to provision a `START1-M` server. Neither `START1-M` nor `X64-4GB` work, I always receive the error `Error in driver during machine creation: X64-4GB wrong commercial type`.

**Comment by izissise** [comment]
This fixed in version 1.6, you can now use any name that are in listed in `https://cp-par1.scaleway.com/products/servers`

**Comment by paulrostorp** [comment]
Same error occurs now with the latest version...
Tried with START1-L, DEV1-XL, DEV1-L...

**Comment by bmedici** [comment]
Same here:
```
docker-machine create -d scaleway \
--scaleway-token=XX --scaleway-organization=XX \
--scaleway-name="test5" --scaleway-commercial-type="START1-S" \
test5
```
Replies:
```
Running pre-create checks...
Creating machine...
(test98) Creating SSH key...
(test98) Creating server...
Error creating machine: Error in driver during machine creation: START1-S wrong commercial type
```
