### ISSUE TITLE
Error creating instance, No such bootscript: docker

### ISSUE THREAD

**Issue by TRYDirect** [scaleway/docker-machine-driver-scaleway#94]
Error creating machine: Error in driver during machine creation: No such bootscript: docker

**Comment by khast3x** [comment]
Any news? This is pretty critical

**Comment by khast3x** [comment]
Option was not available using the AUR package. Worked with the latest git build. Please update repos :pray: 

Best

**Comment by izissise** [comment]
Should be fixed with the latest release, the bootscript used is now the image default
