### ISSUE TITLE
brew installs version 1.3 -> provisioning errors

### ISSUE THREAD

**Issue by iben12** [scaleway/docker-machine-driver-scaleway#98]
The default `brew` install method (as in the readme) installs version 1.3. The current version is 1.6.
```
brew info docker-machine-driver-scaleway
scaleway/scaleway/docker-machine-driver-scaleway: stable 1.3, HEAD
```
I think this explains a lot of issues coming up again and again regarding `--scaleway-commercial-type`, `--scaleway-image` and overall provisioning errors, because these have been fixed in later versions.

Using the `HEAD` installs the usable version:
```
$ brew install scaleway/scaleway/docker-machine-driver-scaleway --HEAD
```

**Comment by izissise** [comment]
Thanks for raising this issue,

This should be fixed with the last commit

**Comment by QuentinBrosse** [comment]
@iben12 You can now upgrade your driver to `1.6`:
